### ISSUE TITLE
Limit stacktrace to not exceed maximum logline size of 16kB

### ISSUE THREAD

**Issue by DanielOber** [it-at-m/refarch-templates#90]
**Is your feature request related to a problem? Please describe.**
Logback JSON Logging - Limit stacktrace to not exceed maximum logline size of 16kB

**Describe the solution you'd like**
Split the log.

**Describe alternatives you've considered**
Ask the Openshift team if there is a docker solution for it.

**Comment by eidottermihi** [comment]
I'd recommend using the [LogstashEncoder `ShortenedThrowableConverter`](https://github.com/logfellow/logstash-logback-encoder?tab=readme-ov-file#customizing-stack-traces) to avoid that huge stracktraces are cut of after 16kb size (effectively destroying the JSON parsing).

This can also be used to exclude mostly irrelevant stacktrace lines (like Reflection) and reverse the stacktrace to show the root cause first (because this is often the most relevant)

Example :

```xml
<encoder class="net.logstash.logback.encoder.LogstashEncoder">
	<throwableConverter
		class="net.logstash.logback.stacktrace.ShortenedThrowableConverter">
		<!-- default max size of one log line in docker is 16kb - UTF8 ~ 1 Character = 1 Byte -->
		<maxLength>8096</maxLength>
		<exclude>sun\.reflect\..*\.invoke.*</exclude>
		<exclude>net\.sf\.cglib\.proxy\.MethodProxy\.invoke</exclude>
		<rootCauseFirst>true</rootCauseFirst>
	</throwableConverter>
</encoder>
```

Happy to provide PR for this
